export default {
  CANVAS_HEIGHT: 756,
  CANVAS_WIDTH: 1396,
  STAGE_WIDTH: 290,
  STAGE_HEIGHT: 450,
  DUPLICATE_X_OFFSET: 10,
  DUPLICATE_Y_OFFSET: 10,
  MAX_STAGES_IN_ROW: 4,
  STAGE_PADDING_X: 60,
  STAGE_PADDING_Y: 30,
  STAGE_TITLE_Y_OFFSET: 24,
  STAGE_BACKGROUND_COLOR: '#fff',
  STAGE_MAX_DISPLAY_ITEMS: 4,
  MAX_STAGES: 12,
  TOP_RIGHT_ICON_SIZE: 20
}