export const emptyProjectNode = {
  'name': 'Add Project',
  'titleYOffset': 24,
  'label': 'A promotion stage must contain at least one project. Create a project template to begin.',
  'labelYOffset': 180,
  'labelWidth': 210,
  'icon': 'pficon pficon pficon-add-circle-o',
  'iconYOffset': 80,
  'fontSize': '70px',
  'iconWidth': 70,
  'buttonLabel': 'Add Project',
  'buttonYOffset': 270,
  'buttonClass': 'btn btn-primary',
  'x': 60,
  'y': 52,
  'id': 1,
  'width': 290,
  'height': 450,
  'backgroundColor': '#fff',
  'invalid': false,
  'selected': false,
  'containerNode': true,
  'emptyProjectNode': true
}