/**
 * Red Hat Open Innovation Labs API
 * A generic model to support automation at all levels of the application and infrastructure lifecycle.
 *
 * OpenAPI spec version: 0.3.0-alpha
 * Contact: rhc-open-innovation-labs@redhat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PVCAssociation', 'model/Route'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PVCAssociation'), require('./Route'));
  } else {
    // Browser globals (root is window)
    if (!root.RedHatOpenInnovationLabsApi) {
      root.RedHatOpenInnovationLabsApi = {};
    }
    root.RedHatOpenInnovationLabsApi.Application = factory(root.RedHatOpenInnovationLabsApi.ApiClient, root.RedHatOpenInnovationLabsApi.PVCAssociation, root.RedHatOpenInnovationLabsApi.Route);
  }
}(this, function(ApiClient, PVCAssociation, Route) {
  'use strict';




  /**
   * The Application model module.
   * @module model/Application
   * @version 0.3.0-alpha
   */

  /**
   * Constructs a new <code>Application</code>.
   * @alias module:model/Application
   * @class
   */
  var exports = function() {
    var _this = this;

















  };

  /**
   * Constructs a <code>Application</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Application} obj Optional instance to populate.
   * @return {module:model/Application} The populated <code>Application</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('base_image')) {
        obj['base_image'] = ApiClient.convertToType(data['base_image'], 'String');
      }
      if (data.hasOwnProperty('base_image_tag')) {
        obj['base_image_tag'] = ApiClient.convertToType(data['base_image_tag'], 'String');
      }
      if (data.hasOwnProperty('build_application_commands')) {
        obj['build_application_commands'] = ApiClient.convertToType(data['build_application_commands'], ['String']);
      }
      if (data.hasOwnProperty('build_tool')) {
        obj['build_tool'] = ApiClient.convertToType(data['build_tool'], 'String');
      }
      if (data.hasOwnProperty('build_image_commands')) {
        obj['build_image_commands'] = ApiClient.convertToType(data['build_image_commands'], ['String']);
      }
      if (data.hasOwnProperty('deploy_image_commands')) {
        obj['deploy_image_commands'] = ApiClient.convertToType(data['deploy_image_commands'], ['String']);
      }
      if (data.hasOwnProperty('context_dir')) {
        obj['context_dir'] = ApiClient.convertToType(data['context_dir'], 'String');
      }
      if (data.hasOwnProperty('scm_url')) {
        obj['scm_url'] = ApiClient.convertToType(data['scm_url'], 'String');
      }
      if (data.hasOwnProperty('scm_type')) {
        obj['scm_type'] = ApiClient.convertToType(data['scm_type'], 'String');
      }
      if (data.hasOwnProperty('scm_ref')) {
        obj['scm_ref'] = ApiClient.convertToType(data['scm_ref'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('labels')) {
        obj['labels'] = ApiClient.convertToType(data['labels'], {'String': 'String'});
      }
      if (data.hasOwnProperty('environment_variables')) {
        obj['environment_variables'] = ApiClient.convertToType(data['environment_variables'], {'String': 'String'});
      }
      if (data.hasOwnProperty('pvc_associations')) {
        obj['pvc_associations'] = ApiClient.convertToType(data['pvc_associations'], [PVCAssociation]);
      }
      if (data.hasOwnProperty('routes')) {
        obj['routes'] = ApiClient.convertToType(data['routes'], [Route]);
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} base_image
   */
  exports.prototype['base_image'] = undefined;
  /**
   * @member {String} base_image_tag
   */
  exports.prototype['base_image_tag'] = undefined;
  /**
   * @member {Array.<String>} build_application_commands
   */
  exports.prototype['build_application_commands'] = undefined;
  /**
   * @member {String} build_tool
   */
  exports.prototype['build_tool'] = undefined;
  /**
   * @member {Array.<String>} build_image_commands
   */
  exports.prototype['build_image_commands'] = undefined;
  /**
   * @member {Array.<String>} deploy_image_commands
   */
  exports.prototype['deploy_image_commands'] = undefined;
  /**
   * @member {String} context_dir
   */
  exports.prototype['context_dir'] = undefined;
  /**
   * @member {String} scm_url
   */
  exports.prototype['scm_url'] = undefined;
  /**
   * @member {String} scm_type
   */
  exports.prototype['scm_type'] = undefined;
  /**
   * @member {String} scm_ref
   */
  exports.prototype['scm_ref'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Object.<String, String>} labels
   */
  exports.prototype['labels'] = undefined;
  /**
   * @member {Object.<String, String>} environment_variables
   */
  exports.prototype['environment_variables'] = undefined;
  /**
   * @member {Array.<module:model/PVCAssociation>} pvc_associations
   */
  exports.prototype['pvc_associations'] = undefined;
  /**
   * @member {Array.<module:model/Route>} routes
   */
  exports.prototype['routes'] = undefined;



  return exports;
}));


