/**
 * Red Hat Open Innovation Labs API
 * A generic model to support automation at all levels of the application and infrastructure lifecycle.
 *
 * OpenAPI spec version: 0.3.0-alpha
 * Contact: rhc-open-innovation-labs@redhat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.RedHatOpenInnovationLabsApi) {
      root.RedHatOpenInnovationLabsApi = {};
    }
    root.RedHatOpenInnovationLabsApi.PersistentVolume = factory(root.RedHatOpenInnovationLabsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PersistentVolume model module.
   * @module model/PersistentVolume
   * @version 0.3.0-alpha
   */

  /**
   * Constructs a new <code>PersistentVolume</code>.
   * @alias module:model/PersistentVolume
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>PersistentVolume</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PersistentVolume} obj Optional instance to populate.
   * @return {module:model/PersistentVolume} The populated <code>PersistentVolume</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('capacity')) {
        obj['capacity'] = ApiClient.convertToType(data['capacity'], 'Number');
      }
      if (data.hasOwnProperty('access_modes')) {
        obj['access_modes'] = ApiClient.convertToType(data['access_modes'], ['String']);
      }
      if (data.hasOwnProperty('nfs_path')) {
        obj['nfs_path'] = ApiClient.convertToType(data['nfs_path'], 'String');
      }
      if (data.hasOwnProperty('nfs_server')) {
        obj['nfs_server'] = ApiClient.convertToType(data['nfs_server'], 'String');
      }
      if (data.hasOwnProperty('reclaim_policy')) {
        obj['reclaim_policy'] = ApiClient.convertToType(data['reclaim_policy'], 'String');
      }
      if (data.hasOwnProperty('labels')) {
        obj['labels'] = ApiClient.convertToType(data['labels'], {'String': 'String'});
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Number} capacity
   */
  exports.prototype['capacity'] = undefined;
  /**
   * @member {Array.<module:model/PersistentVolume.AccessModesEnum>} access_modes
   */
  exports.prototype['access_modes'] = undefined;
  /**
   * @member {String} nfs_path
   */
  exports.prototype['nfs_path'] = undefined;
  /**
   * @member {String} nfs_server
   */
  exports.prototype['nfs_server'] = undefined;
  /**
   * @member {module:model/PersistentVolume.ReclaimPolicyEnum} reclaim_policy
   */
  exports.prototype['reclaim_policy'] = undefined;
  /**
   * @member {Object.<String, String>} labels
   */
  exports.prototype['labels'] = undefined;


  /**
   * Allowed values for the <code>accessModes</code> property.
   * @enum {String}
   * @readonly
   */
  exports.AccessModesEnum = {
    /**
     * value: "ReadWriteOnce"
     * @const
     */
    "ReadWriteOnce": "ReadWriteOnce",
    /**
     * value: "ReadOnlyMany"
     * @const
     */
    "ReadOnlyMany": "ReadOnlyMany",
    /**
     * value: "ReadWriteMany"
     * @const
     */
    "ReadWriteMany": "ReadWriteMany"  };

  /**
   * Allowed values for the <code>reclaim_policy</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ReclaimPolicyEnum = {
    /**
     * value: "Retain"
     * @const
     */
    "Retain": "Retain",
    /**
     * value: "Recycle"
     * @const
     */
    "Recycle": "Recycle"  };


  return exports;
}));


